#!/usr/bin/env python3
"""Generate JotPin's static CommonMark HTML5 named-entity table."""

import html.entities
import json
from pathlib import Path


output = Path(__file__).resolve().parents[1] / "HtmlEntities.js"
entities = {
    "&" + name: value
    for name, value in html.entities.html5.items()
    if name.endswith(";")
}
payload = json.dumps(entities, ensure_ascii=True, sort_keys=True,
                     separators=(",", ":"))
output.write_text(
    ".pragma library\n\n"
    "// Generated by scripts/generate_html_entities.py from Python's HTML5 "
    "entity table.\n"
    f"var namedEntities = {payload}\n\n"
    "function decodeNamed(value) {\n"
    "  var decoded = namedEntities[String(value || \"\")]\n"
    "  return decoded === undefined ? String(value || \"\") : decoded\n"
    "}\n",
    encoding="utf-8",
)
